# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eiv0nZOqb2tBKEKspEqDVYA_cl7QPwA6
"""

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

df = pd.read_csv("/Users/namgyulee/Personal_Project/News_Article_Classification/normalized.csv.csv")
df = df.loc[:, ['Title Sentence Vector', 'Description Sentence Vector', 'Author Sentence Vector']]
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

# Build model
model = Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
    ])

# Train model with the train set
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_set, train_set, epochs=100, batch_size=128)

# Evaluate the model with the test set
loss, accuracy = model.evaluate(test_set, test_set)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

new_df = pd.read_csv("/Users/namgyulee/Personal_Project/News_Article_Classification/Data/new_data.csv")
new_df = new_df.loc[:, ["Title Sentence Vector", 'Description Senetence Vector', 'Author Sentence Vector']]

predicts = model.predict(new_df)
print(predicts)